In [3]:
import numpy as np

In [4]:
A = np.array ([[1,2,-1],[4,6,-2], [-1,3,3]])
print (A)
print(np.linalg.det(A))
print(round(np.linalg.det(A)))



[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]]
-13.999999999999996
-14
