In [27]:
import numpy as np

#Matrix and Its Operations

A = np.array(([-5 , 0], [4 , 1]))
B = np.array(([6 , -3], [2 , 3]))

Sum = np.add(A, B)
Difference1 = np.subtract(A, B)
Difference2 = np.subtract(B, A)

print('The Sum of A and B is', "\n", Sum)
print('-----------')
print('The Difference of A and B is', "\n", Difference1)
print('-----------')
print('The Difference of B and A is', "\n", Difference2)

The Sum of A and B is 
 [[ 1 -3]
 [ 6  4]]
-----------
The Difference of A and B is 
 [[-11   3]
 [  2  -2]]
-----------
The Difference of B and A is 
 [[11 -3]
 [-2  2]]
